### ISSUE TITLE
Hello, author. Is there any academic paper here

### ISSUE THREAD

**Issue by xiejiachen** [ashkonf/hybrid-naive-bayes#1]
Hello, as I am writing an academic report, how can I cite you?

**Comment by ashkonf** [comment]
There isn't a published academic accompanying this work, so I'm not completely sure how to cite it formally. From my perspective, as long as you mention my name a link to this repository that's ok with me. Thanks for checking!

**Comment by xiejiachen** [comment]
@ashkonf  Any example to use, please?

**Comment by ashkonf** [comment]
What format are you using?

**Comment by xiejiachen** [comment]
@ashkonf  .txt

**Comment by xiejiachen** [comment]
example data https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data

**Comment by ashkonf** [comment]
I just added: https://github.com/ashkonf/HybridNaiveBayes/blob/master/src/test.py
