### ISSUE TITLE
Any useage example please

### ISSUE THREAD

**Issue by xiejiachen** [ashkonf/hybrid-naive-bayes#2]
Dear Author:
Could you please give an example with your codes, maybe with 
sample data https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data

Thanks

**Comment by ashkonf** [comment]
I'm happy to put together an example using that data but I'm not sure how to interpret it. How should one interpret the file? Is each of the rows supposed to be a data point? What are the labels?

**Comment by xiejiachen** [comment]
Data instruction is here:
https://archive.ics.uci.edu/ml/datasets/Statlog+(German+Credit+Data)

It is customer credit evaluate, label is the last column. 1 is good and 2 is bad.  All othet columns are features.

**Comment by ashkonf** [comment]
This should do it:
[test.py.zip](https://github.com/ashkonf/HybridNaiveBayes/files/441634/test.py.zip)

**Comment by ashkonf** [comment]
Or check out this for an updated implementation: https://github.com/ashkonf/HybridNaiveBayes/blob/master/src/test.py

**Comment by xiejiachen** [comment]
Excited
