### ISSUE TITLE
Hey author, It seems not work in python3

### ISSUE THREAD

**Issue by xiejiachen** [ashkonf/hybrid-naive-bayes#3]
I just tried to convert it to python 3 codes, but it there is an error report:

```
slice indices must be integers or None or have an __index__ method
```

[codes](https://github.com/xiejiachen/HybridNaiveBayes/tree/master/srcpy3)
And also, could you please give some suggestions about how to print every category variables conditional probabilities based on these codes and output prediction results.

**Comment by ashkonf** [comment]
This library doesn't support Python 3.

The conditional probabilities of features are stored in the classifier's "distributions" property.
